### PR TITLE
Fix/filenames

### LINKED ISSUE #105: [Bug]: Dart filenames
### Describe the bug

The filenames are inconsistent and according to Effective Dart style, they should be lowercase_with_underscores

### To Reproduce

All the `.dart` files

### Expected behavior

Should be lowercase_with_underscores

### Where did you find this problem?

Android

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lenni009**
closes #105 
I hope I got them all, let me know if something is missing

### CODE REVIEW

**Comment by Lenni009** [comment]
Sorry that all your commits are also in there...

**Comment by Khaoz-Topsy** [comment]
Oh damn, if you make the PR into develop it would just be your commits 😋

**Comment by Lenni009** [comment]
good point

**Comment by Lenni009** [comment]
I let you have the honor of merging, that way I can say that I wasn't responsible for any breaking changes 😝

**Comment by Khaoz-Topsy** [comment]
🤦

**Comment by Khaoz-Topsy** [comment]
Getting some red when trying to build on your repo 😕. Can you make the PR into development? Then we can add more to the dumpster fire that is `develop` 😅

**Comment by Lenni009** [comment]
You mean convert to draft?

**Comment by Lenni009** [comment]
Also I think you as repo owner can adjust the PR destination

**Comment by Khaoz-Topsy** [comment]
I don't think so, but I don't know how to do it. I thought that you would have needed to make a new PR 😮 

I was so tempted to squash your commits into 1 to try and preserve the emoji commits, but I will use it as motivation to commit more often 😅

**Comment by Khaoz-Topsy** [comment]
There was only 1 issue, I think your changes are pretty safe, since imports are compile time. So any issues will be from my dumpster fire codes 😂

**Pull request merged**
